name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: false
        type: string
        default: 'dist'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: List files
        run: ls 
      - name: Output contents
        run: echo "Deploying...jobs" 